#@ load("@ytt:data", "data")

secrets:
  sops:
    age_key: #@ data.values.existingAgeKeyContent  
    
    registry:
      hostname: #@ "registry.tanzu.vmware.com" if data.values.platformRegistryLocation == "tanzunetRegistrySelection" else data.values.customPlatformRegistryUrl
      username: #@ data.values.tanzunetUsername if data.values.platformRegistryLocation == "tanzunetRegistrySelection" else data.values.customPlatformRegistryUsername
      password: #@ data.values.tanzunetPassword if data.values.platformRegistryLocation == "tanzunetRegistrySelection" else data.values.customPlatformRegistryPassword

    git:
      basic_auth:
        username: #@ data.values.tapGithubAuthUsername
        password: #@ data.values.tapGithubAuthtoken
