#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")

apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: tap-install
type: kubernetes.io/dockerconfigjson
stringData:
  #@ docker_auth = base64.encode("{}:{}".format(data.values.dockerhubUsername, data.values.INSTALL_REGISTRY_PASSWORD))
  #@ docker_creds = {"username": data.values.dockerhubUsername, "password": data.values.INSTALL_REGISTRY_PASSWORD, "auth": docker_auth}
  .dockerconfigjson: #@ base64.encode(json.encode({"auths": {data.values.INSTALL_REGISTRY_HOSTNAME: docker_creds}}))
      
---