#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")

#@ tanzunetUsername = data.values.tanzunetUsername

---
apiVersion: v1
kind: Secret
metadata:
  name: tanzu-registry
  namespace: tap-install
type: kubernetes.io/dockerconfigjson
data:
  #@ docker_auth = base64.encode("{}:{}".format(data.values.tanzunetUsername, data.values.tanzunetPassword))
  #@ docker_creds = {"username": data.values.tanzunetUsername, "password": data.values.tanzunetPassword, "auth": docker_auth}
  .dockerconfigjson: #@ base64.encode(json.encode({"auths": {data.values.tanzunetUrl: docker_creds}}))