#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")

#! #@ tanzunetUsername = data.values.tanzunetUsername
#! platformRegistryLocation
#! customPlatformRegistrySelection
#! customPlatformRegistryUrl
#! customPlatformRegistryUsername
#! customPlatformRegistryPassword
---
apiVersion: v1
kind: Secret
metadata:
  name: tanzu-registry
  namespace: tap-install
type: kubernetes.io/dockerconfigjson
data:
  #@ if data.values.platformRegistryLocation == 'customPlatformRegistrySelection':
  #@ docker_auth = base64.encode("{}:{}".format(data.values.customPlatformRegistryUsername, data.values.customPlatformRegistryPassword))
  #@ docker_creds = {"username": data.values.customPlatformRegistryUsername, "password": data.values.customPlatformRegistryPassword, "auth": docker_auth}
  .dockerconfigjson: #@ base64.encode(json.encode({"auths": {data.values.customPlatformRegistryUrl: docker_creds}}))
  #@ else: 
  #@ docker_auth = base64.encode("{}:{}".format(data.values.tanzunetUsername, data.values.tanzunetPassword))
  #@ docker_creds = {"username": data.values.tanzunetUsername, "password": data.values.tanzunetPassword, "auth": docker_auth}
  .dockerconfigjson: #@ base64.encode(json.encode({"auths": {data.values.tanzunetUrl: docker_creds}}))
  #@ end