#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")

---
apiVersion: v1
kind: Secret
metadata:
  name: user-registry-dockerconfig
  namespace: tap-install
type: kubernetes.io/dockerconfigjson
data:
  #@ docker_auth = base64.encode("{}:{}".format(data.values.dockerhubUsername, data.values.dockerhubPassword))
  #@ docker_creds = {"username": data.values.dockerhubUsername, "password": data.values.dockerhubPassword, "auth": docker_auth}
  .dockerconfigjson: #@ base64.encode(json.encode({"auths": {data.values.dockerhubUrl: docker_creds}}))
      
