#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")

---
apiVersion: v1
kind: Secret
metadata:
  name: sso-credentials
  namespace: api-portal
type: Opaque
data:
#@ if data.values.springApiPortalOktaIntegrationEnabled == "true"
  client-id: #@ data.values.oktaClientId
  client-secret: #@ data.values.oktaClientSecret
  issuer-uri:  #@ data.values.oktaIssuerUri
  scope:  #@ data.values.oktaScopes
  user-name-attribute:  #@ data.values.oktaUsernameAttribute
#@ end