#@ load("@ytt:data", "data")

tap_install:
    sensitive_values:
        shared:
            #@ if data.values.targetImageRegistryLocation == 'harbor':
            image_registry:
                project_path: #@ data.values.harborDefaultRegistry + '/buildservice'
                username: #@ data.values.harborUsername
                password: #@ data.values.harborPassword
            #@ else:
            image_registry:
                project_path: #@ data.values.dockerhubDefaultRegistry + '/buildservice'
                username: #@ data.values.dockerhubUsername
                password: #@ data.values.dockerhubPassword
            #@ end
        tap_gui:
            app_config:
                auth:
                    allowGuestAccess: true
                    environment: development
                    #@ if data.values.tapPortalAuthProviderEnable:
                    providers:
                        github:
                            development:
                                clientId: #@ data.values.githubClientId
                                clientSecret: #@ data.values.githubClientSecret
                    #@ end
                integrations:
                    github:
                        - host: github.com
                          token: #@ data.values.tapGithubAuthToken