#@ load("@ytt:data", "data")

tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: #@ data.values.dockerhubDefaultRegistry
                username: #@ data.values.dockerhubUsername
                password: #@ data.values.dockerhubPassword
        tap_gui:
            app_config:
                auth:
                    allowGuestAccess: true
                    environment: development
                    providers:
                        github:
                            development:
                                clientId: 18a9ac7f07f81d88760b
                                clientSecret: f29030
                integrations:
                    github:
                        - host: github.com
                          token: ghp_bq