#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-portal-tls-cert.yaml
  namespace: api-portal
spec:
  dnsNames:
  - api-portal.akslab.tap.fynesy.com
  secretName: api-portal-tls-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer